### ISSUE TITLE
Compilation being weird

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [crowplexus/FNF-LegacyPsych#10]
### Describe your problem here.

`'C:\users\(name)\desktop\My' is not recognized as an internal or external command, operable program or batch file.'

The folder I put it in is just called "My mods". I moved the source folder to desktop and it does the same thing, but with a different path.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by crowplexus** [comment]
go to the `art` folder and double click `test_x64-debug.bat`
