### ISSUE TITLE
Centering freeplay difficulty and score text

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [crowplexus/FNF-LegacyPsych#14]
### Describe your problem here.

I don't know how to do this and I have 0 knowledge of Haxe. I also need to know how to make the song text go left and right instead of up and down.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I changed the score and difficulty text.

**Comment by crowplexus** [comment]
sorry but this isn't the place to ask for coding help, you might wanna go to the [Psych Engine Server](https://discord.gg/psychengine) instead
